baseURL: https://anorak.dev/
title: A Certain Universe
languageCode: en-us
theme: m10c

params:
    author: anorak
    description: Food for thought.
    avatar: /avatar.png
    menu_item_separator: <br>

    style:
        darkestColor: "#1f1f1f"
        darkColor: "#2f2f2f"
        lightColor: "#e0e0e0"
        lightestColor: "#ffffff"
        primaryColor: "#FFAFC5"

    social:
    -   name: mail
        url: mailto:noel@anorak.dev
    
    -   name: twitter
        url: https://twitter.com/anoworak
    
    -   name: github
        url: https://github.com/anor4k

menu:
    main:
    -   identifier: posts
        name: Posts
        url: /posts/

    -   identifier: resume
        name: Resume
        url: /resume/
